## Polynomial Regression

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [2]:
df = pd.read_csv('calories.csv')
df.head()

   age  exercise_min  heart_rate  calories_burned
0   56     46.660231  131.951222       149.971814
1   46     53.649343  125.261020       148.528043
2   32     85.317185  122.061045       234.736706
3   60     40.888211  134.771227       130.136709
4   25     86.895245  102.419220       263.670132

In [3]:
# features and target
x = df.iloc[:, 0:3]
y = df.iloc[:, -1]

In [4]:
# scatter plot of True data
# x = age
# y = exercise_min
# z = calories burned

fig = px.scatter_3d(df, x = df['age'], 
                       y = df['exercise_min'], 
                       z = df['calories_burned'],
                       color = df['calories_burned'],
                       color_continuous_scale='viridis',
                       title = '3d plot')
fig

# linear Model training

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=2)
lr = LinearRegression()
lr.fit(x_train, y_train)
y_pred_lr = lr.predict(x_test)

print('Intercept: ',lr.intercept_)
print('Coef: ',lr.coef_)
print('R2 Score: ',r2_score(y_test, y_pred_lr))

Intercept:  -47.83840206509959
Coef:  [ 1.63191991  2.78544747 -0.1728475 ]
R2 Score:  0.8761571184783593

In [6]:
# plane of regression
x_range = np.linspace(df['age'].min(), df['age'].max(), 30)
y_range = np.linspace(df['exercise_min'].min(), df['exercise_min'].max(), 30)

xx, yy = np.meshgrid(x_range, y_range)

heart_mean = df['heart_rate'].mean()
hear_rate_col = np.full(xx.ravel().shape, heart_mean)
pred_input = np.c_[xx.ravel(), yy.ravel(), hear_rate_col]

zz = lr.predict(pred_input).reshape(xx.shape)

fig = px.scatter_3d(df, x = df['age'], 
                       y = df['exercise_min'], 
                       z = df['calories_burned'],
                       color = df['calories_burned'],
                       color_continuous_scale='blues',
                       title = '3d plot')

fig.add_surface(x = x_range, y = y_range, z = zz)

fig.show()

/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/utils/validation.py:2739: UserWarning:

X does not have valid feature names, but LinearRegression was fitted with feature names

# polynomial Features

In [7]:
poly = PolynomialFeatures(degree=2, include_bias=True)
x_train_trans = poly.fit_transform(x_train)
x_test_trans = poly.transform(x_test)

lr2 = LinearRegression()
lr2.fit(x_train_trans, y_train)
y_pred = lr2.predict(x_test_trans)

print('Intercept: ',lr2.intercept_)
print('Coef: ',lr2.coef_)
print('R2 Score: ',r2_score(y_test, y_pred))

Intercept:  -1.5832608933981476
Coef:  [ 0.00000000e+00 -1.57649833e-01  4.48820376e-01  1.75156758e-01
  2.02815032e-02 -5.11277287e-03  3.26258801e-03  3.96432080e-02
 -1.12575223e-02  2.97166158e-04]
R2 Score:  0.9580927425920986

In [10]:
# plane of regression
x_range = np.linspace(df['age'].min(), df['age'].max(), 30)
y_range = np.linspace(df['exercise_min'].min(), df['exercise_min'].max(), 30)

xx, yy = np.meshgrid(x_range, y_range)

heart_mean = df['heart_rate'].mean()
hear_rate_col = np.full(xx.ravel().shape, heart_mean)
pred_input = np.c_[xx.ravel(), yy.ravel(), hear_rate_col]
pred_input_poly = poly.transform(pred_input)
zz = lr2.predict(pred_input_poly).reshape(xx.shape)

fig = px.scatter_3d(df, x = df['age'], 
                       y = df['exercise_min'], 
                       z = df['calories_burned'],
                       color = df['calories_burned'],
                       color_continuous_scale='blues',
                       title = '3d plot')

fig.add_surface(x = x_range, y = y_range, z = zz)

fig.show()

/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/utils/validation.py:2739: UserWarning:

X does not have valid feature names, but PolynomialFeatures was fitted with feature names

In [11]:
df.head()

   age  exercise_min  heart_rate  calories_burned
0   56     46.660231  131.951222       149.971814
1   46     53.649343  125.261020       148.528043
2   32     85.317185  122.061045       234.736706
3   60     40.888211  134.771227       130.136709
4   25     86.895245  102.419220       263.670132

In [15]:
# user input
age = int(input('Enter Age: '))
exercise = float(input('Enter Exercise min: '))
heart_rate_ip = float(input('Enter Heart rate: '))

ip_df = pd.DataFrame({
    'age': [age],
    'exercise_min': [exercise],
    'heart_rate': [heart_rate_ip]
})

ip_poly = poly.transform(ip_df)
prediction = lr2.predict(ip_poly)

print('Prediction:', prediction[0])

Prediction: 44.42622286726645